---
config:
  layout: dagre
  theme: mc
---
flowchart TD
  subgraph subGraph0["Local API Utilities Workflow"]
    B["🔧 GetLocalExerciseSlugs"]
    A["⚙️ ExercismReposRootPath"]
    C("🔧 GetLocalMetadata")
    D("🔧 GetLocalDeprecationNote")
    E["🔍 LocalExercisesWithDetails"]
    F["📄 Output Table"]
  end
  A --> B & C & D
  B --> E
  C --> E
  D --> E
  E --> F
  B@{ shape: proc}
  A@{ shape: manual-input}
  E@{ shape: subproc}
  F@{ shape: doc}
  B:::func
  A:::param
  C:::func
  D:::func
  E:::query
  F:::output
  classDef param fill:#f9f,stroke:#333,stroke-width:2px,color:#333
  classDef func fill:#ccf,stroke:#333,stroke-width:2px,color:#333
  classDef query fill:#cfc,stroke:#333,stroke-width:2px,color:#333
  classDef output fill:#ffc,stroke:#333,stroke-width:2px,color:#333
  style A fill:#BBDEFB
